#!/bin/bash

set -e

ROOT_DIRECTORY="$(dirname "$0")/.."

if ! command -v brew &> /dev/null; then
  echo " --> Installing Homebrew"
  bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
else
  echo " --> Homebrew exists!"
fi

echo " --> Make sure we’re using the latest Homebrew"
brew update

echo " --> Upgrade any already-installed formulae"
brew upgrade

echo " --> Installing Brewfile from $ROOT_DIRECTORY"

pwd
ls

BREWFILE="$ROOT_DIRECTORY/Brewfile"
echo "Brewfile contents:"
sed 's/^/  /' < "$BREWFILE"

brew bundle check "--file=$BREWFILE" || brew bundle install "--file=$BREWFILE"

echo " --> Setting Fisher as the default shell"
chsh -s $(which fish)

echo " --> Remove outdated versions from the cellar"
brew cleanup

echo " --> Done!"