winget install 7zip.7zip
winget install Apple.iTunes
winget install Canonical.Ubuntu
winget install Corsair.iCUE
winget install CPUID.CPU-Z
winget install CPUID.HWMonitor
winget install CrystalDewWorld.CrystalDiskMark
winget install Discord.Discord
winget install Dropbox.Dropbox
winget install GitHub.GitHubDesktop
winget install Google.Chrome
winget install Logitech.LGH
winget install Microsoft.PowerToys
winget install Microsoft.Skype
winget install Microsoft.VisualStudioCode
winget install Notion.Notion
winget install Nvidia.GeForceExperience
winget install qBittorrent.qBittorrent
winget install ResponsivelyApp.ResponsivelyApp
winget install SlackTechnologies.Slack
winget install Spotify.Spotify
winget install VideoLAN.VLC
winget install Zeit.Hyper
